/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fhs;

import javax.swing.JOptionPane;

/**
 *
 * @author Nyko
 */
public class loading extends javax.swing.JFrame {

    /**
     * Creates new form loading
     */
    public loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        loadinglbl = new javax.swing.JLabel();
        CLOSE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1420, 681));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refilling.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 320, 430));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fidel Hasaka Salvador");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 580, 60));

        LoadingValue.setText("0%");
        LoadingValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoadingValueMouseClicked(evt);
            }
        });
        jPanel1.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 30, 20));

        loadingbar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                loadingbarPropertyChange(evt);
            }
        });
        jPanel1.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1010, -1));

        loadinglbl.setText("loading....");
        jPanel1.add(loadinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 370, -1));

        CLOSE.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        CLOSE.setText("X");
        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLOSEMouseClicked(evt);
            }
        });
        jPanel1.add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 20, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loadingbg_1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1420, 681));
        jLabel1.setMinimumSize(new java.awt.Dimension(1420, 681));
        jLabel1.setPreferredSize(new java.awt.Dimension(1420, 681));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1020, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadingbarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_loadingbarPropertyChange
    
    }//GEN-LAST:event_loadingbarPropertyChange

    private void LoadingValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadingValueMouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_LoadingValueMouseClicked

    private void CLOSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CLOSEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       loading sp = new loading();
       sp.setVisible(true);
       
       try{
           for(int i=0;i<=100;i++){
           Thread.sleep(100);
           sp.LoadingValue.setText(i+"%");
           if(i==10){
           sp.loadinglbl.setText("Turning on Data......");
           }
           if(i==20){
           sp.loadinglbl.setText("Sana ako nlng......");
           }
           if(i==50){
           sp.loadinglbl.setText("hindi ka nya na mahal siguro......");
           }
           if(i==70){
           sp.loadinglbl.setText("Happy Friend......");
           }
           if(i==80){
           sp.loadinglbl.setText("Luanching Application......");
           }
           
           sp.loadingbar.setValue(i);
        
           }
           
            
       }catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
       
     
       
       }
         sp.setVisible(false);
         login s = new login();
       s.setVisible(true);
       sp.dispose();
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLOSE;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadinglbl;
    // End of variables declaration//GEN-END:variables


}
