/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fhs;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nyko
 */
public class login extends javax.swing.JFrame {

    private Connection conn = null;
    private PreparedStatement pst = null;
    ResultSet rs = null;
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usericon = new javax.swing.JLabel();
        textUSER = new javax.swing.JTextField();
        user = new javax.swing.JSeparator();
        passicon = new javax.swing.JLabel();
        textPASS = new javax.swing.JPasswordField();
        pass = new javax.swing.JSeparator();
        buttonLOGIN = new javax.swing.JButton();
        CLOSE = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user1.png"))); // NOI18N
        jPanel1.add(usericon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        textUSER.setBorder(null);
        textUSER.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textUSERFocusGained(evt);
            }
        });
        textUSER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textUSERKeyTyped(evt);
            }
        });
        jPanel1.add(textUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 270, 40));
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 270, 10));

        passicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pass1.png"))); // NOI18N
        passicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passiconMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passiconMouseReleased(evt);
            }
        });
        jPanel1.add(passicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        textPASS.setBorder(null);
        textPASS.setPreferredSize(new java.awt.Dimension(63, 16));
        textPASS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPASSFocusGained(evt);
            }
        });
        textPASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textPASSMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                textPASSMouseReleased(evt);
            }
        });
        textPASS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPASSKeyPressed(evt);
            }
        });
        jPanel1.add(textPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 270, 40));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 270, 10));

        buttonLOGIN.setText("LOGIN");
        buttonLOGIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLOGINActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 110, 40));

        CLOSE.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        CLOSE.setText("X");
        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLOSEMouseClicked(evt);
            }
        });
        jPanel1.add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg1.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textUSERFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textUSERFocusGained
        textUSER.setText(null);
    }//GEN-LAST:event_textUSERFocusGained

    private void textUSERKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textUSERKeyTyped
        if(textUSER.getText().length()>0){
            textPASS.setEnabled(true);
        }else{
            textPASS.setEnabled(false);
        }
    }//GEN-LAST:event_textUSERKeyTyped

    private void passiconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passiconMousePressed
        textPASS.setEchoChar((char)0);
    }//GEN-LAST:event_passiconMousePressed

    private void passiconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passiconMouseReleased
 
        textPASS.setEchoChar('*');
    }//GEN-LAST:event_passiconMouseReleased

    private void textPASSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPASSFocusGained
        textPASS.setText(null);
    }//GEN-LAST:event_textPASSFocusGained

    private void textPASSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPASSMousePressed

    }//GEN-LAST:event_textPASSMousePressed

    private void textPASSMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPASSMouseReleased

    }//GEN-LAST:event_textPASSMouseReleased

    private void textPASSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPASSKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            login();
        }
    }//GEN-LAST:event_textPASSKeyPressed

    private void buttonLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLOGINActionPerformed
        login();
    }//GEN-LAST:event_buttonLOGINActionPerformed

    private void CLOSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CLOSEMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conn = DBconnection.conns();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLOSE;
    private javax.swing.JLabel background;
    private javax.swing.JButton buttonLOGIN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator pass;
    private javax.swing.JLabel passicon;
    private javax.swing.JPasswordField textPASS;
    private javax.swing.JTextField textUSER;
    private javax.swing.JSeparator user;
    private javax.swing.JLabel usericon;
    // End of variables declaration//GEN-END:variables
private void login() {
      try{
          java.sql.Statement stm;
          stm = conn.createStatement();
          java.sql.ResultSet rs;
          rs=stm.executeQuery("SELECT * FROM user WHERE BINARY username = '"+textUSER.getText()+ "' AND BINARY password='"+textPASS.getText()+"'");
        
          if(rs.next()){
        waterrefilling1 s= new waterrefilling1();
        s.setVisible(true);
        dispose();
          }else{
              JOptionPane.showMessageDialog(null,"Invalid Credentials");
          }
          }catch(Exception e){
                   JOptionPane.showMessageDialog(null,e);
                  } 
      
    }


}
