/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fhs;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nyko
 */
public class new_customer extends javax.swing.JFrame {

    private Connection conn = null;
    private PreparedStatement pst = null;
    ResultSet rs = null;
    public new_customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        id_number1 = new javax.swing.JTextField();
        c_name1 = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        contact1 = new javax.swing.JTextField();
        save_customer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer (1).png"))); // NOI18N
        jLabel11.setText("NEW CUSTOMER");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 260, 41));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 240, 10));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel12.setText("ID Number:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel13.setText("Customer Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel14.setText("Address:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel15.setText("Contact Number:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        id_number1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id_number1FocusGained(evt);
            }
        });
        id_number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_number1ActionPerformed(evt);
            }
        });
        id_number1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                id_number1PropertyChange(evt);
            }
        });
        id_number1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_number1KeyTyped(evt);
            }
        });
        jPanel1.add(id_number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 220, 30));

        c_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_name1ActionPerformed(evt);
            }
        });
        c_name1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_name1KeyReleased(evt);
            }
        });
        jPanel1.add(c_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 220, 32));

        address1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                address1KeyReleased(evt);
            }
        });
        jPanel1.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 220, 32));

        contact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contact1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact1KeyTyped(evt);
            }
        });
        jPanel1.add(contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 220, 32));

        save_customer.setText("add Customer");
        save_customer.setEnabled(false);
        save_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_customerMouseClicked(evt);
            }
        });
        save_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_customerActionPerformed(evt);
            }
        });
        save_customer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                save_customerPropertyChange(evt);
            }
        });
        jPanel1.add(save_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/watershit_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 260, 140));

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Background.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(230, 130));
        jLabel1.setMinimumSize(new java.awt.Dimension(230, 130));
        jLabel1.setPreferredSize(new java.awt.Dimension(230, 130));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -7, 770, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void get_new_id(){
        try{
            pst = conn.prepareStatement("SELECT MAX(id_number)+1 AS next_id FROM customer");
            rs = pst.executeQuery();
            if(rs.next()){
                double nextId = rs.getDouble("next_id");
                int roundedId = (int) nextId; // Convert to integer to remove decimal places
            id_number1.setText(Integer.toString(roundedId));
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void id_number1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id_number1FocusGained

    }//GEN-LAST:event_id_number1FocusGained

    private void id_number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_number1ActionPerformed
  
    }//GEN-LAST:event_id_number1ActionPerformed

    private void id_number1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_number1KeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))){
            evt.consume(); }
    }//GEN-LAST:event_id_number1KeyTyped

    private void save_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_customerMouseClicked

    }//GEN-LAST:event_save_customerMouseClicked

    private void save_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_customerActionPerformed
        customer();
        id_number1.setText("");
        c_name1.setText("");
        address1.setText("");

        contact1.setText("");

        
    }//GEN-LAST:event_save_customerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       conn = DBconnection.conns();
       retreive_customer();
        get_new_id();
    }//GEN-LAST:event_formWindowOpened

    private void c_name1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_name1KeyReleased
disable2();     
    }//GEN-LAST:event_c_name1KeyReleased

    private void address1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_address1KeyReleased
disable2();           // TODO add your handling code here:
    }//GEN-LAST:event_address1KeyReleased

    private void contact1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact1KeyReleased
disable2();          // TODO add your handling code here:
    }//GEN-LAST:event_contact1KeyReleased

    private void id_number1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_id_number1PropertyChange
    //id_number1.setEditable(false);
    }//GEN-LAST:event_id_number1PropertyChange

    private void contact1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact1KeyTyped
          char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))){
            evt.consume(); }
    }//GEN-LAST:event_contact1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               waterrefilling1 s = new waterrefilling1();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_name1ActionPerformed

    private void save_customerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_save_customerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_save_customerPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1;
    private javax.swing.JTextField c_name1;
    private javax.swing.JTextField contact1;
    private javax.swing.JTextField id_number1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton save_customer;
    // End of variables declaration//GEN-END:variables
private void disable2(){
   if(c_name1.getText().isEmpty()){
     
          save_customer.setEnabled(false);
 
   }
          else if(address1.getText().isEmpty()){
              save_customer.setEnabled(false);
          }
          else if(contact1.getText().isEmpty()){
          save_customer.setEnabled(false);
          }else{
             save_customer.setEnabled(true);
          }

}
    private void customer(){
 
      try{
          String sql = "INSERT INTO customer(id_number,customer_name,address,contact)VALUES(?,?,?,?)";
          pst = conn.prepareStatement(sql);
       
          pst.setString(1,id_number1.getText());
          pst.setString(2,c_name1.getText());
          pst.setString(3,address1.getText());
          pst.setString(4,contact1.getText());
          
          pst.execute();
          JOptionPane.showMessageDialog(null,"info added Successfully");
          
      }catch(Exception e){
  
          JOptionPane.showMessageDialog(null,e);
      }  
    } 
private void retreive_customer(){
        try{
        String sql = "SELECT  id_number AS 'ID Number', customer_name AS 'Customer Name', address AS 'Address', contact AS 'Contact' FROM customer";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();      

        } catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, e);
        }
}



}
