/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fhs;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Nyko
 */
public class update_customer extends javax.swing.JFrame {
 private Connection conn = null;
    private PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form update_customer
     */
    public update_customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        id_number1 = new javax.swing.JTextField();
        c_name1 = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        contact1 = new javax.swing.JTextField();
        update_customer1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer (1).png"))); // NOI18N
        jLabel11.setText("UPDATE CUSTOMER");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 290, 41));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 280, 10));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel12.setText("ID Number:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel13.setText("Customer Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel14.setText("Address:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel15.setText("Contact Number:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        id_number1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id_number1FocusGained(evt);
            }
        });
        id_number1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                id_number1MouseEntered(evt);
            }
        });
        id_number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_number1ActionPerformed(evt);
            }
        });
        id_number1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                id_number1PropertyChange(evt);
            }
        });
        id_number1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_number1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_number1KeyTyped(evt);
            }
        });
        jPanel1.add(id_number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 220, 30));

        c_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_name1ActionPerformed(evt);
            }
        });
        c_name1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_name1KeyReleased(evt);
            }
        });
        jPanel1.add(c_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 220, 32));

        address1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                address1KeyReleased(evt);
            }
        });
        jPanel1.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 220, 32));

        contact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contact1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contact1KeyTyped(evt);
            }
        });
        jPanel1.add(contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 220, 32));

        update_customer1.setText("update Customer");
        update_customer1.setEnabled(false);
        update_customer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_customer1MouseClicked(evt);
            }
        });
        update_customer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_customer1ActionPerformed(evt);
            }
        });
        jPanel1.add(update_customer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/watershit_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 260, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find-my-friend (1)_1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 40, 30));

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Background.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(230, 130));
        jLabel1.setMinimumSize(new java.awt.Dimension(230, 130));
        jLabel1.setPreferredSize(new java.awt.Dimension(230, 130));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -7, 770, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_number1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id_number1FocusGained

    }//GEN-LAST:event_id_number1FocusGained

    private void id_number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_number1ActionPerformed
  
    }//GEN-LAST:event_id_number1ActionPerformed

    private void id_number1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_id_number1PropertyChange
       // id_number1.setEditable(false);
    }//GEN-LAST:event_id_number1PropertyChange

    private void id_number1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_number1KeyTyped
       char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))){
            evt.consume(); }
    }//GEN-LAST:event_id_number1KeyTyped

    private void c_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_name1ActionPerformed

    private void c_name1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_name1KeyReleased
      
    }//GEN-LAST:event_c_name1KeyReleased

    private void address1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_address1KeyReleased
                 // TODO add your handling code here:
    }//GEN-LAST:event_address1KeyReleased

    private void contact1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact1KeyReleased
            // TODO add your handling code here:
    }//GEN-LAST:event_contact1KeyReleased

    private void contact1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contact1KeyTyped
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))){
            evt.consume(); }
    }//GEN-LAST:event_contact1KeyTyped

    private void update_customer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_customer1MouseClicked

    }//GEN-LAST:event_update_customer1MouseClicked

    private void update_customer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_customer1ActionPerformed
        update_customer2();
        retreive_customer1();
        id_number1.setText("");
          c_name1.setText("");
             address1.setText("");
             contact1.setText("");
        
    }//GEN-LAST:event_update_customer1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        waterrefilling1 s = new waterrefilling1();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_number1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_number1MouseEntered
  
    }//GEN-LAST:event_id_number1MouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     conn = DBconnection.conns();
      retreive_customer1();
    }//GEN-LAST:event_formWindowOpened

    private void id_number1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_number1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_id_number1KeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         retrieve_customer();  
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1;
    private javax.swing.JTextField c_name1;
    private javax.swing.JTextField contact1;
    private javax.swing.JTextField id_number1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton update_customer1;
    // End of variables declaration//GEN-END:variables

private void retrieve_customer() {
    try {
        String idNumberText = id_number1.getText().trim();
        if (idNumberText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter an ID number");
            return;
        }

        int idNumber = Integer.parseInt(idNumberText);

        String sql = "SELECT id_number AS 'ID Number', customer_name AS 'Customer Name', address AS 'Address', contact AS 'Contact' FROM customer WHERE id_number = ?";
        pst = conn.prepareStatement(sql);
        pst.setInt(1, idNumber);
        rs = pst.executeQuery();

        if (rs.next()) {
            String customerName = rs.getString("Customer Name");
            String address = rs.getString("Address");
            String contact = rs.getString("Contact");

            // Assuming you have text fields named c_name1, address1, and contact1
            c_name1.setText(customerName);
            address1.setText(address);
            contact1.setText(contact);
             update_customer1.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No customer found for ID number: " + idNumber);
             update_customer1.setEnabled(false);
             c_name1.setText("");
             address1.setText("");
             contact1.setText("");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Invalid ID number format");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
}

 private void update_customer2() {
    try {
        String sql = "UPDATE customer SET id_number = ?, customer_name = ?, address = ?, contact = ? WHERE id_number = ?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, id_number1.getText());
        pst.setString(2, c_name1.getText());
        pst.setString(3, address1.getText());
        pst.setString(4, contact1.getText());
         pst.setString(5, id_number1.getText());// Assuming customer_name is the primary key or unique identifier

        int rowsAffected = pst.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Customer Info Updated");
        } else {
            JOptionPane.showMessageDialog(null, "No customer found for the specified name");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
}

    private void retreive_customer1(){
        try{
        String sql = "SELECT  id_number AS 'ID Number', customer_name AS 'Customer Name', address AS 'Address', contact AS 'Contact' FROM customer";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();      

        } catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, e);
        }
}

}
